import type { Metadata } from "next";
import { ButtonLink } from "@/components/ui/button-link";
import { Container } from "@/components/ui/container";
import { ItineraryView } from "@/components/itinerary/itinerary-view";
import { sampleItinerary } from "@/lib/mock-data";

export const metadata: Metadata = {
  title: "Your itinerary · Voyager",
  description: "A sample day-by-day itinerary generated by Voyager.",
};

export default function ItineraryPage() {
  return (
    <Container className="py-16">
      <div className="mx-auto max-w-3xl">
        <ItineraryView trip={sampleItinerary} />

        <div className="mt-8 flex flex-col gap-4 rounded-3xl border-2 border-foreground/10 bg-surface p-7 text-center sm:flex-row sm:items-center sm:justify-between sm:text-left">
          <p className="font-display text-xl font-semibold">
            Want a plan like this for your own trip? 🧳
          </p>
          <ButtonLink href="/plan" variant="pink" size="lg" className="shrink-0">
            Plan my trip
          </ButtonLink>
        </div>
      </div>
    </Container>
  );
}
