import type { Metadata } from "next";
import { ButtonLink } from "@/components/ui/button-link";
import { Container } from "@/components/ui/container";
import { sampleItinerary } from "@/lib/mock-data";

export const metadata: Metadata = {
  title: "Your itinerary · Voyager",
  description: "A sample day-by-day itinerary generated by Voyager.",
};

const dayColors = ["bg-green", "bg-pink"];

export default function ItineraryPage() {
  const trip = sampleItinerary;

  return (
    <Container className="py-16">
      <div className="mx-auto max-w-3xl">
        <h1 className="font-display mt-2 text-5xl font-semibold">
          {trip.destination}
        </h1>
        <p className="mt-4 text-lg leading-8 text-muted">{trip.summary}</p>

        <div className="mt-6 flex flex-wrap gap-3">
          <Badge>{trip.days.length} days</Badge>
          <Badge>{trip.travelers} travelers</Badge>
          <Badge>{trip.budget}</Badge>
        </div>

        <div className="mt-12 space-y-6">
          {trip.days.map((day, index) => (
            <section
              key={day.day}
              className="rounded-3xl border-2 border-foreground/10 bg-surface p-6 sm:p-8"
            >
              <div className="flex items-center gap-4">
                <span
                  className={`grid h-12 w-12 shrink-0 place-items-center rounded-full border-2 border-foreground/85 font-display text-xl font-semibold text-[var(--ink)] shadow-[0_4px_0_rgba(28,23,18,0.18)] ${dayColors[index % dayColors.length]}`}
                >
                  {day.day}
                </span>
                <h2 className="font-display text-2xl font-semibold">
                  {day.title}
                </h2>
              </div>

              <ul className="mt-6 space-y-4">
                {day.activities.map((activity, i) => (
                  <li key={i} className="flex items-start gap-3">
                    <span
                      aria-hidden
                      className="grid h-10 w-10 shrink-0 place-items-center rounded-full border-2 border-foreground/10 bg-surface-muted text-lg"
                    >
                      {activity.icon}
                    </span>
                    <div>
                      <div className="flex flex-wrap items-baseline gap-x-3 gap-y-1">
                        <span className="rounded-md bg-surface-muted px-2 py-0.5 font-display text-sm font-semibold">
                          {activity.time}
                        </span>
                        <span className="font-display font-semibold">
                          {activity.title}
                        </span>
                      </div>
                      <p className="mt-1 leading-6 text-muted">
                        {activity.description}
                      </p>
                    </div>
                  </li>
                ))}
              </ul>
            </section>
          ))}
        </div>

        <div className="mt-8 flex flex-col gap-4 rounded-3xl border-2 border-foreground/10 bg-surface p-7 text-center sm:flex-row sm:items-center sm:justify-between sm:text-left">
          <p className="font-display text-xl font-semibold">
            Want a plan like this for your own trip? 🧳
          </p>
          <ButtonLink href="/plan" variant="pink" size="lg" className="shrink-0">
            Plan my trip
          </ButtonLink>
        </div>
      </div>
    </Container>
  );
}

function Badge({ children }: { children: React.ReactNode }) {
  return (
    <span className="rounded-full border-2 border-foreground/85 bg-surface px-4 py-1.5 font-display text-sm font-medium shadow-[0_3px_0_rgba(28,23,18,0.12)]">
      {children}
    </span>
  );
}
