import type { Metadata } from "next";
import { ButtonLink } from "@/components/ui/button-link";
import { Container } from "@/components/ui/container";
import { sampleItinerary } from "@/lib/mock-data";

export const metadata: Metadata = {
  title: "Your itinerary · Voyager",
  description: "A sample day-by-day itinerary generated by Voyager.",
}

export default function ItineraryPage() {
  const trip = sampleItinerary;

  return (
    <Container className="py-16 sm:py-24">
      <div className="mx-auto max-w-3xl">
        <span className="text-sm font-medium text-brand">Your itinerary</span>
        <h1 className="mt-2 text-4xl font-semibold tracking-tight">
          {trip.destination}
        </h1>
        <p className="mt-3 text-lg leading-8 text-muted">{trip.summary}</p>

        <div className="mt-6 flex flex-wrap gap-3 text-sm">
          <Badge>{trip.days.length} days</Badge>
          <Badge>{trip.travelers} travelers</Badge>
          <Badge>{trip.budget}</Badge>
        </div>

        <div className="mt-12 space-y-10">
          {trip.days.map((day) => (
            <section key={day.day}>
              <div className="flex items-center gap-3">
                <span className="grid h-9 w-9 place-items-center rounded-full bg-brand text-sm font-semibold text-white">
                  {day.day}
                </span>
                <h2 className="text-xl font-semibold">{day.title}</h2>
              </div>

              <ol className="mt-5 space-y-3 border-l border-border pl-6">
                {day.activities.map((activity, i) => (
                  <li key={i} className="relative">
                    <span
                      aria-hidden
                      className="absolute -left-[1.85rem] top-1 grid h-6 w-6 place-items-center rounded-full bg-surface-muted text-xs"
                    >
                      {activity.icon}
                    </span>
                    <div className="rounded-2xl border border-border bg-surface p-4">
                      <div className="flex items-baseline gap-3">
                        <span className="text-sm font-medium text-brand">
                          {activity.time}
                        </span>
                        <span className="font-medium">{activity.title}</span>
                      </div>
                      <p className="mt-1 text-sm leading-6 text-muted">
                        {activity.description}
                      </p>
                    </div>
                  </li>
                ))}
              </ol>
            </section>
          ))}
        </div>

        <div className="mt-14 flex flex-col gap-3 rounded-3xl border border-border bg-surface p-6 sm:flex-row sm:items-center sm:justify-between">
          <p className="text-muted">Want a plan like this for your own trip?</p>
          <ButtonLink href="/plan" size="lg">
            Plan my trip
          </ButtonLink>
        </div>
      </div>
    </Container>
  );
}

function Badge({ children }: { children: React.ReactNode }) {
  return (
    <span className="rounded-full border border-border bg-surface px-3 py-1 text-muted">
      {children}
    </span>
  );
}
